{
  "documentName": "Test API v12",
  "units": "in",
  "featureCount": 7,
  "features": [
    {
      "index": 2,
      "type": "adsk::fusion::Sketch",
      "name": "Sketch10",
      "isRolledBack": false,
      "details": {
        "profiles_count": 1,
        "curves_count": 6,
        "curves": [
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "-5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "-5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "-5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "-5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": true,
            "startPoint": {
              "x": "5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "-5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": true,
            "startPoint": {
              "x": "-5.00 in",
              "y": "5.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "5.00 in",
              "y": "-5.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          }
        ],
        "plane": {
          "type": "custom_plane",
          "bob": 0
        }
      }
    },
    {
      "index": 3,
      "type": "adsk::fusion::ExtrudeFeature",
      "name": "Extrude6",
      "isRolledBack": false,
      "details": {
        "operation": "3",
        "faces_count": 6,
        "extent": {
          "type": {
            "value": 0,
            "name": "OneSideFeatureExtentType"
          },
          "distance": {
            "side_one": "10.00 in",
            "side_two": null,
            "symmetric": null
          }
        },
        "profile_type": "adsk::fusion::Profile",
        "profile": {
          "type": "profile",
          "data": {
            "area": "<adsk.fusion.AreaProperties; proxy of <Swig Object of type 'adsk::core::Ptr< adsk::fusion::AreaProperties > *' at 0x0000015921856880> >",
            "loops": [
              {
                "isOuter": true,
                "vertices": [
                  {
                    "type": "line",
                    "startPoint": {
                      "x": "5.00 in",
                      "y": "-5.00 in",
                      "z": "0.00 in"
                    },
                    "endPoint": {
                      "x": "5.00 in",
                      "y": "5.00 in",
                      "z": "0.00 in"
                    }
                  },
                  {
                    "type": "line",
                    "startPoint": {
                      "x": "5.00 in",
                      "y": "5.00 in",
                      "z": "0.00 in"
                    },
                    "endPoint": {
                      "x": "-5.00 in",
                      "y": "5.00 in",
                      "z": "0.00 in"
                    }
                  },
                  {
                    "type": "line",
                    "startPoint": {
                      "x": "-5.00 in",
                      "y": "5.00 in",
                      "z": "0.00 in"
                    },
                    "endPoint": {
                      "x": "-5.00 in",
                      "y": "-5.00 in",
                      "z": "0.00 in"
                    }
                  },
                  {
                    "type": "line",
                    "startPoint": {
                      "x": "-5.00 in",
                      "y": "-5.00 in",
                      "z": "0.00 in"
                    },
                    "endPoint": {
                      "x": "5.00 in",
                      "y": "-5.00 in",
                      "z": "0.00 in"
                    }
                  }
                ]
              }
            ]
          }
        }
      }
    },
    {
      "index": 4,
      "type": "adsk::fusion::Sketch",
      "name": "Sketch11",
      "isRolledBack": false,
      "details": {
        "profiles_count": 1,
        "curves_count": 1,
        "curves": [
          {
            "type": "adsk::fusion::SketchCircle",
            "isConstruction": false,
            "centerPoint": {
              "x": "0.00 in",
              "y": "0.00 in",
              "z": "0.00 in"
            },
            "radius": "3.00 in",
            "constraints": []
          }
        ],
        "plane": {
          "type": "base_plane"
        }
      }
    },
    {
      "index": 5,
      "type": "adsk::fusion::ExtrudeFeature",
      "name": "Extrude7",
      "isRolledBack": false,
      "details": {
        "operation": "3",
        "faces_count": 3,
        "extent": {
          "type": {
            "value": 0,
            "name": "OneSideFeatureExtentType"
          },
          "distance": {
            "side_one": "1.00 in",
            "side_two": null,
            "symmetric": null
          }
        },
        "profile_type": "adsk::fusion::Profile",
        "profile": {
          "type": "profile",
          "data": {
            "area": "<adsk.fusion.AreaProperties; proxy of <Swig Object of type 'adsk::core::Ptr< adsk::fusion::AreaProperties > *' at 0x0000015921856B80> >",
            "loops": [
              {
                "isOuter": true,
                "vertices": [
                  {
                    "type": "circle",
                    "center": {
                      "x": "0.00 in",
                      "y": "0.00 in",
                      "z": "0.00 in"
                    },
                    "radius": "3.00 in"
                  }
                ]
              }
            ]
          }
        }
      }
    },
    {
      "index": 6,
      "type": "adsk::fusion::Sketch",
      "name": "Sketch12",
      "isRolledBack": false,
      "details": {
        "profiles_count": 3,
        "curves_count": 5,
        "curves": [
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "-5.00 in",
              "y": "10.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "5.00 in",
              "y": "10.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "5.00 in",
              "y": "10.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "5.00 in",
              "y": "20.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "5.00 in",
              "y": "20.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "-5.00 in",
              "y": "20.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchLine",
            "isConstruction": false,
            "startPoint": {
              "x": "-5.00 in",
              "y": "20.00 in",
              "z": "0.00 in"
            },
            "endPoint": {
              "x": "-5.00 in",
              "y": "10.00 in",
              "z": "0.00 in"
            },
            "constraints": []
          },
          {
            "type": "adsk::fusion::SketchCircle",
            "isConstruction": false,
            "centerPoint": {
              "x": "-5.00 in",
              "y": "20.00 in",
              "z": "0.00 in"
            },
            "radius": "5.00 in",
            "constraints": []
          }
        ]
      }
    },
    {
      "index": 7,
      "type": "adsk::fusion::ExtrudeFeature",
      "name": "Extrude8",
      "isRolledBack": false,
      "details": {
        "operation": "0",
        "faces_count": 3,
        "extent": {
          "type": {
            "value": 0,
            "name": "OneSideFeatureExtentType"
          },
          "distance": {
            "side_one": "1.00 in",
            "side_two": null,
            "symmetric": null
          }
        },
        "profile_type": "adsk::core::ObjectCollection",
        "profile": {
          "type": "collection",
          "items": [
            {
              "type": "profile",
              "data": {
                "area": "<adsk.fusion.AreaProperties; proxy of <Swig Object of type 'adsk::core::Ptr< adsk::fusion::AreaProperties > *' at 0x00000159218572D0> >",
                "loops": [
                  {
                    "isOuter": true,
                    "vertices": [
                      {
                        "type": "line",
                        "startPoint": {
                          "x": "7.509E-08 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        },
                        "endPoint": {
                          "x": "-5.00 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        }
                      },
                      {
                        "type": "line",
                        "startPoint": {
                          "x": "-5.00 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        },
                        "endPoint": {
                          "x": "-5.00 in",
                          "y": "15.00 in",
                          "z": "0.00 in"
                        }
                      }
                    ]
                  }
                ]
              }
            },
            {
              "type": "profile",
              "data": {
                "area": "<adsk.fusion.AreaProperties; proxy of <Swig Object of type 'adsk::core::Ptr< adsk::fusion::AreaProperties > *' at 0x0000015921857A80> >",
                "loops": [
                  {
                    "isOuter": true,
                    "vertices": [
                      {
                        "type": "line",
                        "startPoint": {
                          "x": "-5.00 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        },
                        "endPoint": {
                          "x": "-5.00 in",
                          "y": "15.00 in",
                          "z": "0.00 in"
                        }
                      },
                      {
                        "type": "line",
                        "startPoint": {
                          "x": "7.509E-08 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        },
                        "endPoint": {
                          "x": "-5.00 in",
                          "y": "20.00 in",
                          "z": "0.00 in"
                        }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      }
    }
  ]
}